#------- you may not edit the lines below -------

all:
	(cd src ; $(MAKE) all)
	(cd utils ; $(MAKE) all)

static:
	(cd src ; $(MAKE) static)
	(cd utils ; $(MAKE) all)

clean:
	(cd src ; $(MAKE) clean)
	(cd utils ; $(MAKE) clean)

install_dist:
	installation/mkinstalldirs /usr/share 
	cp dfm /usr/X11R6/bin
	rm -rf /usr/share/dfm
	cp -r share /usr/share/dfm
	cp extensions/dfmext_normal /usr/share/dfm/dfmext
	cp dfm.1x /usr/X11R6/man/man1/

install:
	installation/mkinstalldirs /usr/local/bin /usr/local/share
	installation/mkinstalldirs /usr/local/man/man1
	cp dfm /usr/local/bin
	rm -rf /usr/local/share/dfm
	cp -r share /usr/local/share/dfm
	cp extensions/dfmext_local /usr/local/share/dfm/dfmext
	cp dfm.1x /usr/local/man/man1/

install_user:
	installation/mkinstalldirs $(HOME)/bin
	cp dfm $(HOME)/bin
	cp extensions/dfmext_user $(HOME)/.dfmext

uninstall:
	rm -rf /usr/share/dfm
	rm -rf /usr/local/share/dfm
	rm -f /usr/X11/bin/dfm	
	rm -f /usr/local/bin/dfm	
	rm -f /usr/local/man/man1/dfm.1x
	rm -f /usr/X11/man/man1/dfm.1x

uninstall_user:
	rm -f $(HOME)/bin/dfm
